### ISSUE TITLE
Dependency to old Newtonsoft.Json

### ISSUE THREAD

**Issue by jonashilmersson** [x2find/FacetFilter2Find#1]
Hi,

As this version has a dependency to an old Newtonsoft.Json (≥ 5.0.5 && < 10.0.0), it's not possible to upgrade to a newer version of Episerver.Find.Cms than v12.6.x as the v12.7.x requires >= 10.0.3. 

Is this something you are planning to address?

Brgds

Jonas

**Comment by lindstromhenrik** [comment]
I've updated the Newtonsoft.Json dependency range to < 11.0.0.

/Henrik
